apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
        owner: team-platform
    spec:
      containers:
        - name: engine
          image: gcr.io/dynatrace-demoability/easytrade/engine:151f288
          ports:
            - containerPort: 8080
          env:
            - name: BROKER_HOSTANDPORT
              value: "broker-service:80"
            - name: PROXY_PREFIX
              value: "engine"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: engine
spec:
  type: ClusterIP
  selector:
    app: engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
